var EA_CSS=''
+'.sec{border:1px solid #999;padding:10px 12px;margin-top:2px}'
+'.sh{font-size:12.5px;font-weight:900;border-bottom:1.5px solid #000;padding-bottom:4px;margin-bottom:8px}'
+'.mx{width:100%;border-collapse:collapse;font-size:11.5px}'
+'.mx th{border-bottom:1.5px solid #000;font-size:10.5px;font-weight:800;padding:4px 5px;text-align:left}'
+'.mx td{padding:4px 5px;border-bottom:1px solid #ddd}'
+'.mx .num{text-align:right;white-space:nowrap}'
+'.tiny{font-size:10px;color:#555;font-weight:700}'
+'.wbar{display:inline-block;height:9px;background:#000;vertical-align:middle;margin-right:5px}'
+'.line{font-size:12px;line-height:1.75;margin-top:8px}'
+'.bars{display:grid;grid-template-columns:auto 1fr auto;gap:4px 9px;align-items:center;font-size:12px}'
+'.bars .nm{font-weight:800;white-space:nowrap}'
+'.bars .tr{height:10px;background:#e8e8e8;position:relative}'
+'.bars .tr i{position:absolute;left:0;top:0;bottom:0;background:#000}'
+'.bars .tr i.r{background:#c0392b}'
+'.bars .v{white-space:nowrap;font-weight:700}'
+'.bars .sub{grid-column:1/-1;font-size:11px;color:#333;padding-left:10px;margin-top:-2px;margin-bottom:3px}'
+'.risk{display:grid;grid-template-columns:auto 1fr auto;gap:5px 10px;align-items:baseline;border-top:1px solid #999;margin-top:9px;padding-top:8px;font-size:12px}'
+'.risk .rk{font-size:18px;font-weight:900;line-height:1}'
/* LC_CSS 의 「내 기록」 상자(.why)가 여기 설명 글에도 붙어 테두리가 생기던 것을 벗긴다 */
+'.risk .why{font-size:11px;color:#333;border:none!important;padding:0!important;margin:0!important;display:inline;background:none}'
+'.risk .loss{font-weight:900;font-size:15px;white-space:nowrap}'
+'.risk .loss small{font-size:9.5px;color:#555;font-weight:700;margin-left:2px}'
+'.red{color:#c0392b}'
+'.good{margin-top:8px;font-size:11.5px;border:1px dashed #999;padding:6px 9px}'
+'.sim{margin-top:9px;border:1px solid #999;border-left:3px solid #000;padding:8px 11px;font-size:11.5px}'
+'.sim ul{margin:3px 0 0;padding-left:16px;line-height:1.7}'
+'@media print{.sec{page-break-inside:avoid}}';

